name: thuprai_delivery
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  retrofit: ^4.4.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  get: ^4.6.6
  intl: ^0.19.0
  url_launcher: ^6.3.0
  awesome_dio_interceptor: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  retrofit_generator: ^9.1.2
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png
